const SEARCH_TITLE = 'SEARCH_TITLE';
const RESULT_TITLE = 'RESULT_TITLE';

const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
const GET_PEOPLE_DETAIL = 'GET_PEOPLE_DETAIL';
const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';

const FILTERED_MOST_POPULAR = 'FILTERED_MOST_POPULAR';

export {
    SEARCH_TITLE,
    RESULT_TITLE,
    GET_MOVIE_DETAIL,
    GET_PEOPLE_DETAIL,
    GET_POPULAR_MOVIES,
    FILTERED_MOST_POPULAR
}
