const SEARCH_TITLE = 'SEARCH_TITLE';

const GET_RESULT_TITLE_START = 'GET_RESULT_TITLE_START';
const GET_RESULT_TITLE_SUCCESS = 'GET_RESULT_TITLE_SUCCESS';
const GET_RESULT_TITLE_FAIL = 'GET_RESULT_TITLE_FAIL';

const GET_MOVIE_DETAIL_START = 'GET_MOVIE_DETAIL_START';
const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_DETAIL_FAIL';


const GET_PEOPLE_DETAILS_START = 'GET_PEOPLE_DETAIL_START';
const GET_PEOPLE_DETAIL_SUCCESS = 'GET_PEOPLE_DETAIL_SUCCESS';
const GET_PEOPLE_DETAIL_FAIL = 'GET_PEOPLE_DETAIL_FAIL';


const GET_POPULAR_MOVIES_START = 'GET_POPULAR_MOVIES_START';
const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
const GET_POPULAR_MOVIES_FAIL = 'GET_POPULAR_MOVIES_FAIL';

const FILTERED_MOST_POPULAR = 'FILTERED_MOST_POPULAR';

export {
    SEARCH_TITLE,
    GET_MOVIE_DETAIL_START,
    GET_MOVIE_DETAIL_SUCCESS,
    GET_MOVIE_DETAIL_FAIL,
    GET_PEOPLE_DETAILS_START,
    GET_PEOPLE_DETAIL_SUCCESS,
    GET_PEOPLE_DETAIL_FAIL,
    GET_POPULAR_MOVIES_START,
    GET_POPULAR_MOVIES_SUCCESS,
    GET_POPULAR_MOVIES_FAIL,
    GET_RESULT_TITLE_START,
    GET_RESULT_TITLE_SUCCESS,
    GET_RESULT_TITLE_FAIL,
    FILTERED_MOST_POPULAR
};
