const SEARCH_TITLE = 'SEARCH_TITLE';

const GET_RESULT_TITLE_START = 'GET_RESULT_TITLE_START';
const GET_RESULT_TITLE_SUCCESS = 'GET_RESULT_TITLE_SUCCESS';
const GET_RESULT_TITLE_FAIL = 'GET_RESULT_TITLE_FAIL';

const GET_MOVIE_DETAIL_START = 'GET_MOVIE_DETAIL_START';
const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_DETAIL_FAIL';

const CREDITS = 'CREDITS';
const EXTERNAL_ID = 'EXTERNAL_ID' ;

const GET_PERSON_DETAIL_START = 'GET_PERSON_DETAIL_START';
const GET_PERSON_DETAIL_SUCCESS = 'GET_PERSON_DETAIL_SUCCESS';
const GET_PERSON_DETAIL_FAIL = 'GET_PERSON_DETAIL_FAIL';
const GET_PERSON_MOVIE_CREDITS = 'GET_PERSON_MOVIE_CREDITS';
const GET_PERSON_TV_CREDITS = 'GET_PERSON_TV_CREDITS';


const GET_MOVIES_START = 'GET_MOVIES_START';
const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

const GET_SIMILAR_MOVIES_START = 'GET_SIMILAR_MOVIES_START';
const GET_SIMILAR_MOVIES_SUCCESS = 'GET_SIMILAR_MOVIES_SUCCESS';
const GET_SIMILAR_MOVIES_FAIL = 'GET_SIMILAR_MOVIES_FAIL';

const FILTERED_MOST_POPULAR = 'FILTERED_MOST_POPULAR';

const SEARCH_RESULT = 'SEARCH_RESULT';

export {
    SEARCH_TITLE,
    GET_MOVIE_DETAIL_START,
    GET_MOVIE_DETAIL_SUCCESS,
    GET_MOVIE_DETAIL_FAIL,
    GET_PERSON_DETAIL_START,
    GET_PERSON_DETAIL_SUCCESS,
    GET_PERSON_DETAIL_FAIL,
    GET_PERSON_MOVIE_CREDITS,
    GET_PERSON_TV_CREDITS,
    GET_MOVIES_START,
    GET_MOVIES_SUCCESS,
    GET_MOVIES_FAIL,
    GET_RESULT_TITLE_START,
    GET_RESULT_TITLE_SUCCESS,
    GET_RESULT_TITLE_FAIL,
    GET_SIMILAR_MOVIES_START,
    GET_SIMILAR_MOVIES_SUCCESS,
    GET_SIMILAR_MOVIES_FAIL,
    FILTERED_MOST_POPULAR,
    SEARCH_RESULT,
    EXTERNAL_ID,
    CREDITS
};
